---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    silent: true
    cmds:
    - pinact run
    - yamlfmt .
    - actionlint -shellcheck shellcheck
    - ghalint run
    - ghalint act

  ci:
    silent: true
    cmds:
    - git clone --depth 1 --branch feat/ip7z/7zip https://github.com/takumin/aqua-registry.git aqua-registry
    #######################################################################################################
    # aqua policy
    #######################################################################################################
    - cmd: aqua policy allow "aqua-registry/aqua-policy.yaml"
    #######################################################################################################
    # aqua registry
    #######################################################################################################
    - cmd: cd "aqua-registry" && aqua g -i ip7z/7zip
    #######################################################################################################
    # aqua install
    #######################################################################################################
    - cmd: cd "aqua-registry" && aqua install -a
    #######################################################################################################
    # p7zip version
    #######################################################################################################
    - cmd: cd "aqua-registry" && aqua exec 7za
    #######################################################################################################
    # download 7z archive
    #######################################################################################################
    - cmd: cd "aqua-registry" && curl -fsSLO "https://github.com/ip7z/7zip/releases/download/24.09/7z2409-src.7z"
    #######################################################################################################
    # extract 7z archive
    #######################################################################################################
    - cmd: cd "aqua-registry" && aqua exec 7za x 7z2409-src.7z
    #######################################################################################################
    # file tree 7z
    #######################################################################################################
    - cmd: tre "aqua-registry"
