---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    silent: true
    cmds:
    - pinact run
    - yamlfmt .
    - actionlint -shellcheck shellcheck
    - ghalint run
    - ghalint act

  ci:
    silent: true
    cmds:
    - git clone --depth 1 --branch feat/ip7z/7zip https://github.com/takumin/aqua-registry.git aqua-registry
    #######################################################################################################
    # aqua policy
    #######################################################################################################
    - cmd: aqua policy allow "aqua-registry/aqua-policy.yaml"
      platforms: [darwin]
    - cmd: aqua policy allow "aqua-registry/aqua-policy.yaml"
      platforms: [linux]
    - cmd: aqua policy allow "aqua-registry/aqua-policy.yaml"
      platforms: [windows]
    #######################################################################################################
    # aqua install
    #######################################################################################################
    - cmd: cd "aqua-registry" && aqua install -a
      platforms: [darwin]
    - cmd: cd "aqua-registry" && aqua install -a
      platforms: [linux]
    - cmd: cd "aqua-registry" && aqua install -a
      platforms: [windows]
