---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    silent: true
    cmds:
    - pinact run
    - yamlfmt .
    - actionlint -shellcheck shellcheck
    - ghalint run
    - ghalint act
