---
name: CI
on:
  push:
  pull_request:
permissions: {}
jobs:
  ci:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: 'darwin/amd64'
          runner: 'macos-13'
        - name: 'darwin/arm64'
          runner: 'macos-15'
        - name: 'linux/amd64'
          runner: 'ubuntu-24.04'
        - name: 'linux/arm64'
          runner: 'ubuntu-24.04-arm'
        - name: 'windows/amd64'
          runner: 'windows-2025'
    name: CI (${{ matrix.name }})
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.50.0
        aqua_opts: -a
    - name: Running task
      run: task
    - name: Checkout feat/ip7z/7zip
      run: git clone --depth 1 https://github.com/takumin/aqua-registry.git
    - name: Installing p7zip
      run: cd aqua-registry && aqua i -a
